# These are supported funding model platforms

github: skellat
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: smkellat
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: smkellat
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # REDACTED

