# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "ELP Television" 
subtitle: Media for the Ashtabula area  
email: ashtabulaecv197@gmail.com
lang: en-us
author: Erie Looking Productions
#description: "Lighting the way from Ashtabula to see television history when basic broadcast TV goes sour.  This is our very special 'Push VOD' proto-network."
description: "Online television network offering public domain and Creative Commons-licensed video content from the Internet Archive in addition to Ashtabula-area produced shows."
#description: "The irregularly up"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coyote.works" # the base hostname & protocol for your site
twitter_username: writer_smk
github_username:  skellat

permalink: /:year/:title.html

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['forceout', 'ChangeLog', 'CNAME', 'README.md', 'CODE_OF_CONDUCT.md', 'CONTRIBUTING.md', 'SECURITY.md', 'LICENSE', 'docs', 'Gemfile.lock', 'Gemfile']

# Timezone

timezone: America/Detroit
